#
# Autogenerated by Thrift Compiler (1.0.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING


module proxy

using Compat
using Thrift
import Thrift.process, Thrift.meta, Thrift.distribute




export meta
export PartialKey # enum
export TablePermission # enum
export SystemPermission # enum
export NamespacePermission # enum
export ScanType # enum
export ScanState # enum
export ConditionalStatus # enum
export Durability # enum
export CompactionType # enum
export CompactionReason # enum
export IteratorScope # enum
export TimeType # enum
export Key # struct
export ColumnUpdate # struct
export DiskUsage # struct
export KeyValue # struct
export ScanResult # struct
export Range # struct
export ScanColumn # struct
export IteratorSetting # struct
export ScanOptions # struct
export BatchScanOptions # struct
export KeyValueAndPeek # struct
export KeyExtent # struct
export Column # struct
export Condition # struct
export ConditionalUpdates # struct
export ConditionalWriterOptions # struct
export ActiveScan # struct
export ActiveCompaction # struct
export WriterOptions # struct
export CompactionStrategyConfig # struct
export UnknownScanner # exception
export UnknownWriter # exception
export NoMoreEntriesException # exception
export AccumuloException # exception
export AccumuloSecurityException # exception
export TableNotFoundException # exception
export TableExistsException # exception
export MutationsRejectedException # exception
export NamespaceExistsException # exception
export NamespaceNotFoundException # exception
export NamespaceNotEmptyException # exception
export AccumuloProxyProcessor, AccumuloProxyClient, AccumuloProxyClientBase, login, addConstraint, addSplits, attachIterator, checkIteratorConflicts, clearLocatorCache, cloneTable, compactTable, cancelCompaction, createTable, deleteTable, deleteRows, exportTable, flushTable, getDiskUsage, getLocalityGroups, getIteratorSetting, getMaxRow, getTableProperties, importDirectory, importTable, listSplits, listTables, listIterators, listConstraints, mergeTablets, offlineTable, onlineTable, removeConstraint, removeIterator, removeTableProperty, renameTable, setLocalityGroups, setTableProperty, splitRangeByTablets, tableExists, tableIdMap, testTableClassLoad, pingTabletServer, getActiveScans, getActiveCompactions, getSiteConfiguration, getSystemConfiguration, getTabletServers, removeProperty, setProperty, testClassLoad, authenticateUser, changeUserAuthorizations, changeLocalUserPassword, createLocalUser, dropLocalUser, getUserAuthorizations, grantSystemPermission, grantTablePermission, hasSystemPermission, hasTablePermission, listLocalUsers, revokeSystemPermission, revokeTablePermission, grantNamespacePermission, hasNamespacePermission, revokeNamespacePermission, createBatchScanner, createScanner, hasNext, nextEntry, nextK, closeScanner, updateAndFlush, createWriter, update, flush, closeWriter, updateRowConditionally, createConditionalWriter, updateRowsConditionally, closeConditionalWriter, getRowRange, getFollowing, systemNamespace, defaultNamespace, listNamespaces, namespaceExists, createNamespace, deleteNamespace, renameNamespace, setNamespaceProperty, removeNamespaceProperty, getNamespaceProperties, namespaceIdMap, attachNamespaceIterator, removeNamespaceIterator, getNamespaceIteratorSetting, listNamespaceIterators, checkNamespaceIteratorConflicts, addNamespaceConstraint, removeNamespaceConstraint, listNamespaceConstraints, testNamespaceClassLoad # service AccumuloProxy

include("proxy_constants.jl")
include("proxy_types.jl")
include("proxy_impl.jl")  # server methods to be hand coded
include("AccumuloProxy.jl")


end # module proxy
